#!/bin/sh
set -e
export DEBIAN_FRONTEND=noninteractive

# juju doesn't set this, but node-gyp requires it (probably).
export HOME=${HOME:-~root}
export INTERNAL_IP="$(/sbin/ifconfig | grep 'inet addr:10\.' | sed 's/.*addr:\([^ ]*\).*/\1/')"

juju-log "Configuring custard..."
sh hooks/050_config_custard_upstart.r.sh

juju-log "Configuring nginx..."
sh hooks/015_config_nginx.r.sh

juju-log "Configuring munin..."
munin_server=$(config-get MUNIN_SERVER)

juju-log "Setting up git cache..."
sh hooks/010_setup_git_daemon.r.sh

if ! grep -q $munin_server /etc/munin/munin-node.conf
then
    echo "cidr_allow ${munin_server}/32" >> /etc/munin/munin-node.conf
fi
