#!/bin/sh
set -e
export DEBIAN_FRONTEND=noninteractive

# juju doesn't set this, but node-gyp requires it (probably).
export HOME=${HOME:-~root}

juju-log "Configuring custard..."
sh hooks/050_config_custard_upstart.r.sh

juju-log "Configuring nginx..."
sh hooks/015_config_nginx.r.sh
