#!/bin/bash
set -e

# juju doesn't set this, but node-gyp requires it (probably).
export HOME=${HOME:-~root}

export DEBIAN_FRONTEND=noninteractive
# export STORAGE_DIR=$(config-get CO_STORAGE_DIR)
export JUJU_UNIT_NAME="$JUJU_UNIT_NAME"
export HOSTNAME=${JUJU_UNIT_NAME/\//-}

juju-log "Installing common software..."
sh hooks/install_common.sh

juju-log "Installing oidentd..."
sh hooks/080_install_oidentd.r.sh
juju-log "Installing node..."
sh hooks/027_install_node.r.sh

# Setup custard
juju-log "Setting up nginx..."
sh hooks/015_setup_nginx.r.sh
juju-log "Setting up custard..."
sh hooks/050_setup_custard.r.sh
