#!/bin/sh
REDIS_PASSWORD=$(relation-get password)
REDIS_SERVER=$(relation-get private-address)

mkdir -p /etc/custard
# Store in file, so that config-changed can read them.
echo "$REDIS_PASSWORD" > /etc/custard/redis-password
echo "$REDIS_SERVER" > /etc/custard/redis-server

# Edit cobalt.conf on the fly.
sed -i.tmp -e "/export REDIS_PASSWORD/s/=.*/=$REDIS_PASSWORD/" /etc/init/custard.conf
sed -i.tmp -e "/export REDIS_SERVER/s/=.*/=$REDIS_SERVER/" /etc/init/custard.conf
# restart server
stop custard
start custard
