#!/bin/sh
REDIS_PASSWORD=$(relation-get password)
sed -i.tmp -e "/export REDIS_PASSWORD/s/=.*/=$REDIS_PASSWORD/" /etc/init/custard.conf
REDIS_SERVER=$(relation-get private-address)
sed -i.tmp -e "/export REDIS_SERVER/s/=.*/=$REDIS_SERVER/" /etc/init/custard.conf
