#!/bin/sh

(
  export GOPATH=/opt/mailcheck/
  go get -u github.com/scraperwiki/mailcheck
  go install github.com/scraperwiki/mailcheck
)

export MAILCHECK_HOST="$(config-get MAILCHECK_HOST)"
export MAILCHECK_PASSWORD="$(config-get MAILCHECK_PASSWORD)"
export MAILCHECK_FREQUENCY="$(config-get MAILCHECK_FREQUENCY)"

sh hooks/config/mailcheck-upstart.conf.shmpl > /etc/init/mailcheck.conf

cat <<EOF > /etc/nginx/sites-available/mailcheck
server {
     ssl_certificate      star_scraperwiki_com.crt;
     ssl_certificate_key  star_scraperwiki_com.key;
     listen 443 ssl;
     server_name ${MAILCHECK_HOST};
     access_log /var/log/nginx/mailcheck.access.log;
     location / {
         proxy_pass              http://127.0.0.1:5983;
         proxy_set_header        Host \$host;
         proxy_set_header        X-Real-IP \$remote_addr;
         proxy_set_header        X-Forwarded-For \$proxy_add_x_forwarded_for;
         proxy_set_header        X-Forwarded-Host \$host;
         proxy_set_header        X-Forwarded-Port \$server_port;
     }
}
EOF

ln -sf /etc/nginx/sites-available/mailcheck /etc/nginx/sites-enabled/mailcheck || true

if pgrep nginx > /dev/null
then
	service nginx reload
else
	service nginx start
fi

service mailcheck restart
