#!/bin/sh

if ! which nginx >/dev/null 2>&1
then
	echo "We're assuming you're going to run this on a server with nginx already installed. Sorry."
	exit 1
fi

apt-add-repository -y ppa:duh/golang

apt-get update -y
apt-get install -y golang 

open-port 443/TCP
