#!/bin/bash
LOG=/var/log/pam_script.log
echo "$PAM_USER login" >> $LOG

groups=$(id -Gn "$PAM_USER")
if [ "${groups#databox}" == "$groups" ]
then
  echo "$PAM_USER ignored" >> $LOG
  exit 0
fi

mkdir -p /jails/$PAM_USER > /dev/null 2>&1

have_mounts_changed=false

MemoryLimit=$((512*1024*1024))
CpuTime=10000
CpuPeriod=100000
if [ ! -d /sys/fs/cgroup/cpu/$PAM_USER ]
then
  cgcreate -t $PAM_USER -g memory,cpu,cpuacct:$PAM_USER
fi
echo $MemoryLimit > /sys/fs/cgroup/memory/$PAM_USER/memory.limit_in_bytes
echo 12 > /sys/fs/cgroup/cpu/$PAM_USER/cpu.shares
echo $CpuPeriod > /sys/fs/cgroup/cpu/$PAM_USER/cpu.cfs_period_us
echo $CpuTime > /sys/fs/cgroup/cpu/$PAM_USER/cpu.cfs_quota_us

echo $PPID > /sys/fs/cgroup/cpu/$PAM_USER/tasks
echo $PPID > /sys/fs/cgroup/memory/$PAM_USER/tasks
echo $PPID > /sys/fs/cgroup/cpuacct/$PAM_USER/tasks

# mount an fs if it's not already mounted
trymount () {
  eval mount_dir=\${$#}

  if ! grep -qP "${mount_dir}\b" /var/db/mounts
  then
    mount "$@"
    have_mounts_changed=true
  fi
} >> $LOG 2>&1

trymount --bind /opt/basejail /jails/$PAM_USER
trymount --bind /var/spool/cron/crontabs /jails/$PAM_USER/var/spool/cron/crontabs
trymount --bind /ebs/home/$PAM_USER /jails/$PAM_USER/home
trymount --bind /dev /jails/$PAM_USER/dev
trymount --bind /dev/pts /jails/$PAM_USER/dev/pts
trymount --bind /proc /jails/$PAM_USER/proc

if $have_mounts_changed
then
  echo "Mounts have changed..." >> $LOG
  (
    flock -w 2 9 || exit 99
    cp /proc/mounts /var/db/mounts+
    mv /var/db/mounts+ /var/db/mounts
  ) 9>/var/db/mounts.lock
fi
