# Check syntax with:
# python -c "import yaml;yaml.load(open('config.yaml'))"
options:
  MAILCHECK_PASSWORD:
    type: string
    description: "Password for mailcheck@scraperwiki.com"
  MAILCHECK_HOST:
    type: string
    description: "Server name for nginx"
  MAILCHECK_FREQUENCY:
    type: string
    description: "Expected frequency of incoming e-mails (determines error condition)"
