#!/bin/sh
set -e
export DEBIAN_FRONTEND=noninteractive
export STORAGE_DIR=$(config-get CO_STORAGE_DIR)

juju-log "Configuring cobalt..."
sh hooks/029_config_cobalt.r.sh

juju-log "Configuring nginx..."
sh hooks/015_config_nginx.r.sh

juju-log "Configuring monit..."
sh hooks/config_monit.sh

juju-log "Configuring munin..."
munin_server=$(config-get MUNIN_SERVER)

juju-log "Configuring PAM..."
cp hooks/config/pam.d-sshd /etc/pam.d/sshd
cp hooks/config/pam.d-su /etc/pam.d/su
cp hooks/config/pam_script_ses_open /usr/share/libpam-script

if ! grep -q $munin_server /etc/munin/munin-node.conf
then
  echo "cidr_allow ${munin_server}/32" >> /etc/munin/munin-node.conf
fi


# TODO: add TOOLS_RSA and TOOLS_RSA_PUB to charms config
#       probably a good time to cp all the charm configs for each service
mkdir -p /opt/basejail/tools/.ssh
# if not in files, add entries
#tools:x:110:115::/opt/basejail/tools:/bin/bash
#tools:x:115:

config-get TOOLS_RSA_PUB > /opt/basejail/tools/.ssh/authorized_keys
